runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /static
  static_dir: static/static
- url: /(.*\.(gif|png|jpg|js|json|ico))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|js|json|ico)$
- url: /.*
  static_files: static/index.html
  upload: static/index.html

builtins:
- remote_api: on

skip_files:
- .*node_modules
- .*vendor
- .*project-name-having-too-many-files